yarn workspace utils add @babel/core@7.14.8 -D
yarn workspace utils add @babel/plugin-proposal-class-static-block@7.14.5 -D
yarn workspace utils add @babel/plugin-proposal-decorators@7.14.5 -D
yarn workspace utils add @babel/plugin-proposal-do-expressions@7.14.5 -D
yarn workspace utils add @babel/plugin-proposal-export-default-from@7.14.5 -D
yarn workspace utils add @babel/plugin-proposal-function-bind@7.14.5 -D
yarn workspace utils add @babel/plugin-proposal-function-sent@7.14.5 -D
yarn workspace utils add @babel/plugin-proposal-partial-application@7.14.5 -D
yarn workspace utils add @babel/plugin-proposal-pipeline-operator@7.14.8 -D
yarn workspace utils add @babel/plugin-proposal-private-property-in-object@7.14.5 -D
yarn workspace utils add @babel/plugin-proposal-record-and-tuple@7.14.5 -D
yarn workspace utils add @babel/plugin-proposal-throw-expressions@7.14.5 -D
yarn workspace utils add @babel/plugin-syntax-bigint@7.8.3 -D
yarn workspace utils add @babel/preset-env@7.14.8 -D
yarn workspace utils add @babel/preset-react@7.14.5 -D
yarn workspace utils add @babel/preset-typescript@7.14.5 -D
yarn workspace utils add @svgr/webpack@6.2.1 -D
yarn workspace utils add @types/lodash@4.14.182 -D
yarn workspace utils add @types/react@17.0.47 -D
yarn workspace utils add @types/react-dom@17.0.16 -D
yarn workspace utils add @types/react-router-dom@5.3.3 -D
yarn workspace utils add babel-loader@8.2.5 -D
yarn workspace utils add copy-webpack-plugin@11.0.0 -D
yarn workspace utils add cross-env@7.0.3 -D
yarn workspace utils add css-loader@6.7.1 -D
yarn workspace utils add html-webpack-plugin@5.5.0 -D
yarn workspace utils add portfinder@1.0.28 -D
yarn workspace utils add typescript@4.6.3 -D
yarn workspace utils add webpack@5.72.0 -D
yarn workspace utils add webpack-bundle-analyzer@4.5.0 -D
yarn workspace utils add webpack-dev-server@4.8.1 -D
yarn workspace utils add webpack-merge@5.8.0 -D
